# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ] # mainブランチに対してのプッシュの場合に実行

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4 # リポジトリからソースコードを取得します

    - name: Set up Go 
      uses: actions/setup-go@v4 # Goの開発環境を設定します
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build main.go

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: test
        release_name: Release test
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false